; Spotify
global SPOTIFY_DIR := A_AppData . "\Spotify\Spotify.exe"
global SPOTIFY_VOLUME_X_OFFSET := 130
global SPOTIFY_VOLUME_Y_OFFSET := 37
global SPOTIFY_X_AXIS := 1920 ; fullscreen
global SPOTIFY_Y_AXIS := 1040 ; fullscreen
global SPOTIFY_VOLUME_MIN := 0
global SPOTIFY_VOLUME_MAX := 75
global SPOTIFY_VOLUME := Floor(SPOTIFY_VOLUME_MAX / 2)
global SPOTIFY_VOLUME_X_LOCATION := SPOTIFY_X_AXIS - SPOTIFY_VOLUME_X_OFFSET
global SPOTIFY_VOLUME_Y_LOCATION := SPOTIFY_Y_AXIS - SPOTIFY_VOLUME_Y_OFFSET